a = int(input('Digite um valor: '))
b = (a*2)
c = (a*3)
d = (a**0.5)
print('O dobro de {} vale {}'.format(a, b))
print('O triplo de {} eh {}'.format(a, c))
print('A raiz quadrada de {} vale {:.2f}'.format(a, d))